services:
  sdigf-db:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sdigf_db
    volumes:
      - sdigf_db_data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d:ro
    networks:
      - dokploy-network

  sdigf-emqx:
    image: emqx/emqx:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: 127.0.0.1
    volumes:
      - sdigf_emqx_data:/opt/emqx/data
    networks:
      - dokploy-network

volumes:
  sdigf_db_data:
  sdigf_emqx_data:

networks:
  dokploy-network:
    external: true