services:
  sdigf-db:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sdigf_db
    volumes:
      - sdigf_db_data:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d:ro
    networks:
      - dokploy-network

  sdigf-mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - sdigf_mosquitto_data:/mosquitto/data
    networks:
      - dokploy-network

volumes:
  sdigf_db_data:
  sdigf_mosquitto_data:

networks:
  dokploy-network:
    external: true